name: Java CI with Maven

on:
  push:
    branches: [ master ]
    paths:
      - 'agent/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Cache Docker layers
        uses: actions/cache@v2.1.7
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-agent-buildx-${{ hashFiles('**/Dockerfile') }}
          restore-keys: ${{ runner.os }}-agent-buildx-${{ hashFiles('**/Dockerfile') }}

      - name: Docker Metadata action
        id: docker-meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ secrets.DOCKER_HUB_NAME }}/agent
          tags: ${{ github.run_number }}

      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
          logout: true

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: agent/.
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
